/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users
         * @description Список пользователей с фильтрацией по направлению и подразделению.
         *
         *     Доступ:
         *     - администратор -> все пользователи;
         *     - руководитель -> он сам + вся его ветка подчинённых;
         *     - сотрудник без подчинённых -> только он сам.
         */
        get: operations["get_users_api_v1_users_get"];
        put?: never;
        /**
         * Create User
         * @description Создать нового пользователя.
         */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Получить конкретного пользователя.
         *
         *     Доступ:
         *     - admin -> любой;
         *     - пользователь -> сам себя;
         *     - руководитель -> свою ветку.
         */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Удалить пользователя.
         */
        delete: operations["delete_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Departments */
        get: operations["get_departments_api_v1_departments_get"];
        put?: never;
        /** Create Department */
        post: operations["create_department_api_v1_departments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/my-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Department Tree
         * @description Возвращает дерево, доступное текущему пользователю.
         *
         *     ADMIN:
         *         получает всю структуру.
         *
         *     LEADER:
         *         получает свои подразделения и всё их поддерево.
         *
         *     EMPLOYEE:
         *         получает 403.
         */
        get: operations["get_my_department_tree_api_v1_departments_my_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{department_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Department */
        get: operations["get_department_api_v1_departments__department_id__get"];
        put?: never;
        post?: never;
        /** Delete Department */
        delete: operations["delete_department_api_v1_departments__department_id__delete"];
        options?: never;
        head?: never;
        /** Update Department */
        patch: operations["update_department_api_v1_departments__department_id__patch"];
        trace?: never;
    };
    "/api/v1/permissions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Permissions
         * @description Отдаёт текущему пользователю его собственные права: какие
         *     подразделения и каких пользователей он может видеть/вести.
         *
         *     Формат ответа соответствует тому, что уже ждёт фронтенд
         *     (frontend/src/api/permissions.ts, MOCK_PERMISSIONS) — этот
         *     эндпоинт можно подключать напрямую, без правок типов на фронте.
         */
        get: operations["get_my_permissions_api_v1_permissions_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список всех навыков компании */
        get: operations["get_skills_api_v1_skills_get"];
        put?: never;
        /** Создать новый навык компании */
        post: operations["create_skill_api_v1_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Редактировать существующий навык */
        patch: operations["update_skill_api_v1_skills__skill_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить навыки в годовой план развития сотрудника */
        post: operations["add_skills_to_plan_api_v1_users__user_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить историю 1:1 встреч */
        get: operations["get_meetings_history_api_v1_meetings_get"];
        put?: never;
        /** Сохранить новый протокол 1:1 встречи */
        post: operations["create_meeting_api_v1_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Редактировать существующий протокол встречи */
        patch: operations["update_meeting_api_v1_meetings__meeting_id__patch"];
        trace?: never;
    };
    "/api/v1/analytics/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить аналитику и динамику развития сотрудника */
        get: operations["get_user_analytics_api_v1_analytics_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/department/{department_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить сводные метрики по подразделению */
        get: operations["get_department_analytics_api_v1_analytics_department__department_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** DepartmentAnalyticsRead */
        DepartmentAnalyticsRead: {
            /**
             * Department Id
             * @description ID анализируемого подразделения
             */
            department_id: number;
            /**
             * Completion Rate
             * @description Процент выполнения планов развития командой (от 0.0 до 100.0)
             * @example 72.5
             */
            completion_rate: number;
            /**
             * Open Problems Count
             * @description Количество текущих открытых проблем у сотрудников в этом отделе
             * @example 5
             */
            open_problems_count: number;
            /**
             * Total Planned Skills
             * @description Общее количество запланированных скиллов у всех сотрудников подразделения суммарно
             * @example 48
             */
            total_planned_skills: number;
        };
        /** DepartmentCreate */
        DepartmentCreate: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /** Leader Id */
            leader_id?: number | null;
        };
        /** DepartmentResponse */
        DepartmentResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
            /** Leader Id */
            leader_id: number | null;
        };
        /** DepartmentUpdate */
        DepartmentUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: number | null;
            /** Leader Id */
            leader_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeetingCreate */
        MeetingCreate: {
            /**
             * Participant Id
             * @description ID сотрудника, с кем проводится встреча
             */
            participant_id: number;
            /**
             * Meeting Date
             * Format: date-time
             * @description Дата и время проведения встречи
             */
            meeting_date: string;
            /**
             * Summary Markdown
             * @description Подробные итоги встречи в формате Markdown
             */
            summary_markdown: string;
            /**
             * Files And Links
             * @description Массив ссылок или путей к прикрепленным файлам
             * @default []
             */
            files_and_links: string[];
            /**
             * Assessments
             * @description Список оценок навыков, переданных лидом
             * @default []
             */
            assessments: components["schemas"]["SkillAssessment"][];
            /**
             * Global Problem Comment
             * @description Текст общей проблемы по сотруднику в целом
             */
            global_problem_comment?: string | null;
        };
        /** MeetingRead */
        MeetingRead: {
            /**
             * Participant Id
             * @description ID сотрудника, с кем проводится встреча
             */
            participant_id: number;
            /**
             * Meeting Date
             * Format: date-time
             * @description Дата и время проведения встречи
             */
            meeting_date: string;
            /**
             * Summary Markdown
             * @description Подробные итоги встречи в формате Markdown
             */
            summary_markdown: string;
            /**
             * Files And Links
             * @description Массив ссылок или путей к прикрепленным файлам
             * @default []
             */
            files_and_links: string[];
            /**
             * Id
             * @description ID встречи из базы данных
             */
            id: number;
            /**
             * Interviewer Id
             * @description ID руководителя, который провел встречу
             */
            interviewer_id: number;
        };
        /** MeetingUpdate */
        MeetingUpdate: {
            /**
             * Meeting Date
             * @description Новая дата и время
             */
            meeting_date?: string | null;
            /**
             * Summary Markdown
             * @description Обновленный текст итогов в Markdown
             */
            summary_markdown?: string | null;
            /**
             * Files And Links
             * @description Обновленный массив ссылок/файлов
             */
            files_and_links?: string[] | null;
            /**
             * Assessments
             * @description Обновленный список оценок навыков
             */
            assessments?: components["schemas"]["SkillAssessment"][] | null;
            /**
             * Global Problem Comment
             * @description Обновленный текст общей проблемы
             */
            global_problem_comment?: string | null;
        };
        /** MonthlyHistoryItem */
        MonthlyHistoryItem: {
            /**
             * Month
             * @description Год и месяц в формате YYYY-MM
             * @example 2026-09
             */
            month: string;
            /**
             * Count
             * @description Количество успешно подтвержденных навыков в этом месяце
             * @example 3
             */
            count: number;
        };
        /** PermissionsResponse */
        PermissionsResponse: {
            /** User Id */
            user_id: number;
            /** Is Admin */
            is_admin: boolean;
            /** Visible Department Ids */
            visible_department_ids: number[];
            /** Visible User Ids */
            visible_user_ids: number[];
        };
        /** PlanItemCreate */
        PlanItemCreate: {
            /**
             * Skill Id
             * @description ID подключаемого скилла из справочника
             */
            skill_id: number;
            /**
             * Target Date
             * Format: date
             * @description Плановая дата, до которой нужно подтвердить готовность
             */
            target_date: string;
        };
        /** PlanItemRead */
        PlanItemRead: {
            /** Id */
            id: number;
            skill: components["schemas"]["SkillRead"];
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            status: components["schemas"]["SkillStatusEnum"];
            /**
             * Confirmed At
             * @description Фактическая дата выполнения
             */
            confirmed_at?: string | null;
            /**
             * Problem Comment
             * @description Комментарий к проблеме (если статус PROBLEM)
             */
            problem_comment?: string | null;
        };
        /** SkillAssessment */
        SkillAssessment: {
            /**
             * Skill Id
             * @description ID оцениваемого скилла из справочника
             */
            skill_id: number;
            /**
             * Is Completed
             * @description Флаг: успешно ли выполнен/подтвержден навык на встрече
             * @default false
             */
            is_completed: boolean;
            /**
             * Has Problem
             * @description Флаг: зафиксирована ли проблема по этому навыку
             * @default false
             */
            has_problem: boolean;
            /**
             * Comment
             * @description Комментарий к оценке или описание проблемы
             */
            comment?: string | null;
        };
        /** SkillCreate */
        SkillCreate: {
            /**
             * Name
             * @description Название навыка
             * @example FastAPI & Asyncio
             */
            name: string;
            /**
             * Direction Id
             * @description ID направления (BACK/FRONT/QA) из дерева структуры
             */
            direction_id: number;
        };
        /** SkillRead */
        SkillRead: {
            /**
             * Name
             * @description Название навыка
             * @example FastAPI & Asyncio
             */
            name: string;
            /**
             * Direction Id
             * @description ID направления (BACK/FRONT/QA) из дерева структуры
             */
            direction_id: number;
            /** Id */
            id: number;
        };
        /**
         * SkillStatusEnum
         * @enum {string}
         */
        SkillStatusEnum: "PLANNED" | "COMPLETED" | "IN TRAINING" | "PROBLEM";
        /** SkillUpdate */
        SkillUpdate: {
            /**
             * Name
             * @description Новое название навыка
             */
            name?: string | null;
            /**
             * Direction Id
             * @description Новый ID направления
             */
            direction_id?: number | null;
        };
        /** UserAnalyticsRead */
        UserAnalyticsRead: {
            /**
             * User Id
             * @description ID сотрудника
             */
            user_id: number;
            /**
             * Overdue Skills Count
             * @description Количество скиллов в плане, по которым просрочена плановая дата подтверждения
             * @example 2
             */
            overdue_skills_count: number;
            /**
             * Monthly Dynamics
             * @description История подтверждения навыков по месяцам (массив для построения графика)
             * @default []
             */
            monthly_dynamics: components["schemas"]["MonthlyHistoryItem"][];
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "BACK" | "FRONT" | "QA";
            /** Email */
            email?: string | null;
            /** Department Id */
            department_id?: number | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string | null;
            /** Full Name */
            full_name: string;
            /** Direction */
            direction: string;
            /** Department Id */
            department_id: number | null;
            /** Is Admin */
            is_admin: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Direction */
            direction?: ("BACK" | "FRONT" | "QA") | null;
            /** Email */
            email?: string | null;
            /** Department Id */
            department_id?: number | null;
            /** Is Admin */
            is_admin?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users_api_v1_users_get: {
        parameters: {
            query?: {
                direction?: string | null;
                department_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_departments_api_v1_departments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"][];
                };
            };
        };
    };
    create_department_api_v1_departments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_department_tree_api_v1_departments_my_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_department_api_v1_departments__department_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_department_api_v1_departments__department_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_department_api_v1_departments__department_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_permissions_api_v1_permissions_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionsResponse"];
                };
            };
        };
    };
    get_skills_api_v1_skills_get: {
        parameters: {
            query?: {
                direction_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_skill_api_v1_skills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_skill_api_v1_skills__skill_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_skills_to_plan_api_v1_users__user_id__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanItemCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meetings_history_api_v1_meetings_get: {
        parameters: {
            query?: {
                participant_id?: number | null;
                interviewer_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meeting_api_v1_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_meeting_api_v1_meetings__meeting_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_analytics_api_v1_analytics_user__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAnalyticsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_department_analytics_api_v1_analytics_department__department_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentAnalyticsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
