"""add tg_chat_id to users

Revision ID: 60ae28b88bfd
Revises: 0003
Create Date: 2026-09-11 08:31:11.752850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60ae28b88bfd'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_chat_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_chat_id')
    # ### end Alembic commands ###
